services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: carswheels
      POSTGRES_PASSWORD: carswheels123
      POSTGRES_DB: car_wheels_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service

  auth-service:
    build: ./auth
    ports:
      - "8090:8090"
    env_file:
      - ./auth/.env
    depends_on:
      - postgres

volumes:
  postgres_data: